### ISSUE TITLE
레시피 데이터 크롤링

### ISSUE THREAD

**Issue by ahyz0569** [ahyz0569/STS#2]
식재료 이미지 데이터 구축 전 요리에 자주 사용되는 요리재료가 무엇인지 파악하자

**Comment by ahyz0569** [comment]
3/8일
- 테스트로 레시피 30개 크롤링 해서 Dataframe에 추가하는 코드 구현 완료

Dataframe 컬럼 추가 및 텍스트 전처리 부분 추가 후 공유할 예정

**Comment by ahyz0569** [comment]
> 3/8일
> 
> * 테스트로 레시피 30개 크롤링 해서 Dataframe에 추가하는 코드 구현 완료
> 
> Dataframe 컬럼 추가 및 텍스트 전처리 부분 추가 후 공유할 예정

**Comment by ahyz0569** [comment]
3/9일
- 레시피 크롤링 과정 중 요리 재료 조회 부분에서 다른 태그(dl/dt/dd)로 작성된 코드 발견
- [ ] 사용된 태그에 따라 그에 맞게 크롤링 할 수 있도록 예외 처리 진행

**Comment by ahyz0569** [comment]
3/24(수) 할 일

- [ ] 크롤링한 레시피 데이터의 컬럼 정리하기

**Comment by zooyaa** [comment]
- crawling_real.csv 파일에서 'steps', 'steps_img', 'ingredients_tagged', 'main_tagged', 'sub_tagged' 컬럼 추가
- top_ingredients.csv(가장 많이 사용된 식재료), top_main.csv(가장 많이 사용된 주재료) 파일 생성

**Comment by qweqwz** [comment]
3/25(수)
- crawling 데이터 정리 후 최종 원본 만들기 : 완료 사진이 빠져서 csv파일 취합 후 재크롤링 실행

**Comment by qweqwz** [comment]
3/26(목)

- [ ] csv파일 추가된 컬럼들 하나의 파일로 합치기
