### ISSUE TITLE
이미지 분류 모델 검증 및 확정

### ISSUE THREAD

**Issue by ahyz0569** [ahyz0569/STS#5]
식재료 분류 이미지 모델 타당성 검증 현황에 대해 기록해주세요.

**Comment by zooyaa** [comment]
object detection은 파이썬 detecto 패키지 활용 예정 - 이미지 annotation은 LabelImg 툴 사용

**Comment by zooyaa** [comment]
object detection에 사용될 이미지 파일 이름 통일

**Comment by qweqwz** [comment]
3/26(목)

- [ ] object detection 학습에 사용할 이미지 라벨링하기

**Comment by zooyaa** [comment]
object detection 테스트 모델(클래스 6개) 생성 - 테스트 모델 학습중(3/26 17:20 ~)

**Comment by zooyaa** [comment]
> object detection 테스트 모델(클래스 6개) 생성 - 테스트 모델 학습중(3/26 17:20 ~)
> 식재료 감지 및 분류 모델 v2 - 성능 조절 중, 모델 학습 대략 1시간 소요

**Comment by zooyaa** [comment]
식재료 감지 및 분류 모델 v2 - 성능 조절 중, 모델 학습 대략 1시간 소요

**Comment by zooyaa** [comment]
- 식재료 감지 및 분류 모델 v3 - 가장 잘 감지되는 식재료 1개 감지
- 식재료 클래스 3개 추가 예정 - 추가된 클래스로 모델 재학습 예정(4/10)

**Comment by zooyaa** [comment]
> * 식재료 감지 및 분류 모델 v2 - 가장 잘 감지되는 식재료 1개 감지
> * 식재료 클래스 3개 추가 예정 - 추가된 클래스로 모델 재학습 예정(4/10)

식재료 클래스 2개 추가 - 모델 학습중(4/10 ~)

**Comment by zooyaa** [comment]
**클래스('carrot', 'cucumber') 추가후 학습 결과**
- 이미지 데이터셋이 제대로 추가되지 않은 것 같음 - labels 변수에 추가된 클래스가 나오지 않은 것으로 확인
- learning rate를 조정해서 학습 - 학습 결과 정확도가 낮아 재조정 후 다시 학습시킬 예정

**Comment by zooyaa** [comment]
**클래스('carrot', 'cucumber') 추가한 모델 수정후 재학습 결과**
- 학습 결과 loss가 높아 data augmentation 으로 데이터를 늘여 성능을 높일 예정
- 데이터셋 자체도 조금씩 늘일 예정

**Comment by zooyaa** [comment]
**모델 v4 학습중**
- 데이터 크롤러 생성해 이미지 데이터 크롤링 후 기존 학습 데이터에 추가 - 1차(4/16)

**Comment by zooyaa** [comment]
> **모델 v4 학습중**
> 
> * 데이터 크롤러 생성해 이미지 데이터 크롤링 후 기존 학습 데이터에 추가 - 1차(4/16)

- 학습 도중에 gpu 충돌로 인해 학습 중지됨(4/16)
- 다른 모델 학습중(4/20)
