### ISSUE TITLE
레시피 추천 시스템 분석 및 구축

### ISSUE THREAD

**Issue by ahyz0569** [ahyz0569/STS#6]
[03.24,화]
- 비회원
1. 재료(Match)
2. Viewer 우선

- 회원
1. 재료
2. 북마크 우선(유사도)

**Comment by qweqwz** [comment]
3/25(수)
- 전처리한 메인재료 (ingre_main_oneline)로 tf-idf를 활용한 추천시스템 test

- [ ] 26일에는 더 적합한 레시피가 추천될 수 있도록 다른 방법을 찾아볼 것.
